name: Auto update version files

on:
  push:
    paths:
      - 'cal/p.html'
      - 'cal/caltest.html'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update p.version.txt
        if: contains(github.event.head_commit.message, 'p.html')
        run: |
          date +%s > cal/p.version.txt

      - name: Update caltest.version.txt
        if: contains(github.event.head_commit.message, 'caltest.html')
        run: |
          date +%s > cal/caltest.version.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add cal/*.version.txt
          git commit -m "Auto-update version files"
          git push
